name: Daily Python Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # Runs daily at 8:00 AM Madrid time (7:00 AM UTC during standard time)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python pricetracker.py # Replace with your script's filename
